//! SEED Design tokens (daangn/seed-design, Apache-2.0), vendored under
//! `design/seed/` and compiled into `tokens`.

// Generated by `gen`; `rustfmt::skip` keeps `cargo fmt` from reformatting it
// and breaking the byte comparison in the generator test.
#[rustfmt::skip]
pub mod tokens;

pub mod theme;
pub mod widgets;

#[cfg(test)]
pub mod snapshot;

// `gen` is a reserved word in edition 2024, so the module gets another name
// (which still starts with `gen`, keeping `cargo test ui::seed::gen` working).
#[cfg(test)]
#[path = "gen.rs"]
mod generator;
